### ISSUE TITLE
Update to non-RC TRB 2.1

### ISSUE THREAD

**Issue by brennana** [trailblazer/trailblazer-future#9]
It would be quite helpful if this bridge gem were updated for a newer non-RC version of TRB 2.1, since it has been officially released. There seem to be some large differences in how activities are defined in this RC1 bridge gem and current TRB 2.1, namely that modules are used instead of classes, among other breaking differences.

Certainly, to make the jump to TRB 2.1 would be smoother if this gem helped bridge into the official TRB 2.1 API, rather than the outdated RC1. I wouldn't expect further updates after this (it is a bridge gem after all), but converting to 2.1.rc1 still requires additional conversion to 2.1 proper!

Thank you for your consideration.

**Comment by contentfree** [comment]
Came across this tonight… it's difficult to move to 2.1 when the bridge gem doesn't support 2.1. Specifically, I'm trying to follow the "It Works" migration guide and it says to use this gem for the soft deprecation.

**Comment by emaglio** [comment]
Here a PR for this issue https://github.com/trailblazer/trailblazer-future/pull/10 - could you guys test it please?
